### ISSUE TITLE
reCaptcha enterprise

### ISSUE THREAD

**Issue by TheGP** [dzmitry-duboyski/2captcha-ts#11]
Does the lib support passing enterprise: 1?
And what does it do with parameters it doesn't know? Does it send it too or remove it from the request?

**Comment by dzmitry-duboyski** [comment]
@TheGP Yes, supports `enterprise: 1`:
```javascript
solver.recaptcha({
    pageurl: 'https://2captcha.com/ru/demo/recaptcha-v2-enterprise',
    googlekey: '6Lf26sUnAAAAAIKLuWNYgRsFUfmI-3Lex3xT5N-s',
    enterprise: 1
})
.then((res) => {
    console.log(res);
})
```

Unknown parameters should also be sent to the API.
