### ISSUE TITLE
Enlaces en README.{lang}.md

### ISSUE THREAD

**Issue by kratzky** [dzmitry-duboyski/2captcha-ts#2]
El readme en español contiene un enlace al articulo sobre Geetest v4 con un prefijo `ru` y la version china también tiene este prefijo. Y el otro sobre reCAPTCHA v3 dirige al articulo en ruso.

**Comment by dzmitry-duboyski** [comment]
@kratzky hi, fixed it in commit c287a47. Now the links should be correct. Check please if this links correct now.
@kratzky thanks for reporting the wrong links. 

Screenshot (file `README.es.md`):
![image](https://user-images.githubusercontent.com/38065632/222959047-c8994210-c850-49d8-8490-ebfef57e7f3f.png)

Screenshot (file `README.zh.md`):
![image](https://user-images.githubusercontent.com/38065632/222959206-574f7cb8-b3c7-453b-bce5-a0849a9d3798.png)

**Comment by kratzky** [comment]
¡Todo bien, gracias!
